# Generated by Django 5.2.14 on 2026-06-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تنظیمات')),
                ('domain', models.CharField(max_length=300, verbose_name='دامنه سایت')),
                ('url', models.CharField(max_length=300, verbose_name='آدرس سایت')),
                ('email', models.EmailField(max_length=500, verbose_name='ایمیل سایت')),
                ('tel', models.IntegerField(max_length=11, verbose_name='تلفن ثابت')),
                ('phone', models.IntegerField(max_length=11, verbose_name='موبایل')),
                ('about_img1', models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='تصویر 1')),
                ('about_img2', models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='تصویر 2')),
                ('about_img3', models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='تصویر 3')),
                ('about_text1', models.TextField(blank=True, max_length=2000, null=True, verbose_name='متن درباره ما 1')),
                ('about_text2', models.TextField(blank=True, max_length=2000, null=True, verbose_name='متن درباره ما 2')),
                ('about_text3', models.TextField(blank=True, max_length=2000, null=True, verbose_name='متن درباره ما 3')),
                ('is_default', models.BooleanField(default=False, verbose_name='تنظیمات اصلی ؟')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
