# Generated by Django 5.2.14 on 2026-06-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی فوتر لینک',
                'verbose_name_plural': 'دسته بتدی های فوتر لینک',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ftitle', models.CharField(max_length=200, verbose_name='عنوان فوتر لینک')),
                ('url', models.URLField(verbose_name='آدرس')),
                ('footer_link_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_settings.footerlinkbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
    ]
