# Generated by Django 5.2.14 on 2026-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
    ]
