# Generated by Django 5.2.14 on 2026-07-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0040_remove_productcomment_parent_id'),
        ('site_settings', '0003_alter_footerlink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='product_category_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='دسته بندی دارای لینک'),
            preserve_default=False,
        ),
    ]
