# Generated by Django 5.2.14 on 2026-07-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_footerlink_product_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='product_category_url',
        ),
    ]
