# Generated by Django 5.2.14 on 2026-07-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_footerlink_product_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
    ]
