# Generated by Django 5.2.14 on 2026-07-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0040_remove_productcomment_parent_id'),
        ('site_settings', '0008_alter_footerlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='product_category_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='دسته بندی دارای لینک'),
        ),
    ]
