# Generated by Django 5.2.14 on 2026-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_alter_footerlink_product_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ورژن سایت'),
        ),
    ]
