# Generated by Django 5.2.14 on 2026-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_sitesettings_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس سایت'),
        ),
    ]
