# Generated by Django 5.2.14 on 2026-07-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_alter_sitesettings_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(max_length=500, verbose_name='ایمیل سایت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='تلفن ثابت'),
        ),
    ]
