# Generated by Django 5.2.14 on 2026-07-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_alter_sitesettings_email_alter_sitesettings_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='merchant_id',
            field=models.CharField(max_length=1000 ,blank=True, null=True, verbose_name='مرچنت آیدی درگاه'),
        ),
    ]
