# Generated by Django 5.2.14 on 2026-07-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_sitesettings_merchant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='merchant_id',
        ),
    ]
