# Generated by Django 5.2.14 on 2026-07-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_remove_sitesettings_merchant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_img1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_img2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_img3',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text3',
        ),
    ]
