# Generated by Django 5.2.14 on 2026-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='عنوان اسلاید')),
                ('desc', models.CharField(max_length=200, null=True, verbose_name='نوشته')),
                ('banner', models.ImageField(null=True, upload_to='sliders', verbose_name='بنر اسلاید')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
