# Generated by Django 5.2.14 on 2026-07-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_sliderslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال؟'),
        ),
        migrations.AddField(
            model_name='sliderslide',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='اسلاید اصلی؟'),
        ),
    ]
