# Generated by Django 5.2.14 on 2026-07-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_sliderslide_is_active_sliderslide_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderslide',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='sliders', verbose_name='بنر اسلاید'),
        ),
        migrations.AlterField(
            model_name='sliderslide',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نوشته'),
        ),
        migrations.AlterField(
            model_name='sliderslide',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان اسلاید'),
        ),
    ]
