# Generated by Django 5.2.14 on 2026-07-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0005_alter_sliderslide_banner_alter_sliderslide_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان کاروزل کالا')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='carousels', verbose_name='بنر')),
            ],
        ),
    ]
