# Generated by Django 5.2.14 on 2026-07-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0006_carousel'),
        ('product_module', '0052_alter_productcomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'کاروزل', 'verbose_name_plural': 'کاروزل ها'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='فعال / غیرفعال'),
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.carousel', verbose_name='زیر مجموعه کاروزل؟')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'آیتم کاروزل',
                'verbose_name_plural': 'آیتم های کاروزل',
            },
        ),
    ]
