# Generated by Django 5.2.14 on 2026-07-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0007_alter_carousel_options_carousel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_set', to='home_module.carousel', verbose_name='زیر مجموعه کاروزل؟'),
        ),
    ]
