# Generated by Django 5.2.14 on 2026-07-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0008_alter_carouselitem_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='emoji',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ایموجی'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='icon',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس در صورت نیاز'),
        ),
    ]
