# Generated by Django 5.2.14 on 2026-07-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0009_carousel_emoji_carousel_icon_carousel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='color_bg',
            field=models.CharField(blank=True, default='#fff', max_length=100, null=True, verbose_name='رنگ قالب'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='color_fore',
            field=models.CharField(blank=True, default='#fff', max_length=100, null=True, verbose_name='رنگ متن'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='switch_on_break',
            field=models.BooleanField(db_index=True, default=False, verbose_name='سوییچ به رنگ قالب در موبایل'),
        ),
    ]
