# Generated by Django 5.2.14 on 2026-07-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0010_carousel_color_bg_carousel_color_fore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='desc',
            field=models.CharField(max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان کاروزل کالا'),
        ),
    ]
