# Generated by Django 5.2.14 on 2026-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0011_alter_carousel_desc_alter_carousel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderslide',
            name='url',
            field=models.CharField(max_length=1000, null=True, verbose_name='url اسلایدر'),
        ),
    ]
