# Generated by Django 5.2.14 on 2026-07-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0012_sliderslide_url'),
        ('product_module', '0053_product_only_in_qaemshahr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='بلاک کارت ها')),
                ('icon', models.ImageField(null=True, upload_to='cards_block', verbose_name='آیکون')),
                ('url_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='مرتبط با دسته')),
            ],
            options={
                'verbose_name': 'بلاک کارت ها',
            },
        ),
        migrations.CreateModel(
            name='HomeCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.cardblock', verbose_name='بلاک کارت ها')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productsubcategory', verbose_name='مرتبط با دسته')),
            ],
        ),
    ]
