# Generated by Django 5.2.14 on 2026-07-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0013_cardblock_homecards'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecards',
            name='cover',
            field=models.ImageField(db_index=True, null=True, upload_to='card_images', verbose_name='تصویر'),
        ),
    ]
