# Generated by Django 5.2.14 on 2026-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0014_homecards_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardblock',
            name='seo_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم برای سئو(درصورت نیاز)'),
        ),
    ]
