# Generated by Django 5.2.14 on 2026-07-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0015_cardblock_seo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardblock',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال؟'),
        ),
        migrations.AlterField(
            model_name='homecards',
            name='card_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardblock_set', to='home_module.cardblock', verbose_name='بلاک کارت ها'),
        ),
    ]
