# Generated by Django 5.2.14 on 2026-07-29 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0016_cardblock_is_active_alter_homecards_card_block'),
        ('product_module', '0053_product_only_in_qaemshahr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('seo_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام برای سئو')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس url')),
                ('image', models.ImageField(upload_to='home_banner', verbose_name='تصویر')),
                ('desc', models.TextField(blank=True, max_length=100, null=True, verbose_name='توضیحات (درصورت نیاز)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='مربوط به شاخه اصلی؟')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productsubcategory', verbose_name='مربوط به زیرشاخه؟')),
            ],
            options={
                'verbose_name': 'بنر صفحه اصلی',
                'verbose_name_plural': 'بنر های صفحه اصلی',
            },
        ),
    ]
