# Generated by Django 5.2.14 on 2026-07-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0017_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال؟'),
        ),
    ]
