# Generated by Django 5.2.14 on 2026-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0018_banner_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderslide',
            name='title',
        ),
        migrations.AlterField(
            model_name='sliderslide',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نوشته'),
        ),
    ]
