# Generated by Django 5.2.14 on 2026-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0019_remove_sliderslide_title_alter_sliderslide_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوشته pill-bar')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوشته اصلی')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوشته کوچک')),
                ('banner', models.ImageField(null=True, upload_to='sliders', verbose_name='بنر اسلاید')),
                ('url', models.CharField(max_length=1000, null=True, verbose_name='url اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
            ],
            options={
                'verbose_name': 'لندینگ پیج',
                'verbose_name_plural': 'لندینگ پیج ها',
            },
        ),
        migrations.DeleteModel(
            name='SliderSlide',
        ),
    ]
