# Generated by Django 6.0.5 on 2026-05-09 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logo/', verbose_name='')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_imgs/', verbose_name='عکس دسته بندی')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'شاخه اصلی',
                'verbose_name_plural': 'شاخه های اصلی',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان زیرشاخه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory_imgs/', verbose_name='عکس زیر شاخه')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='عنوان در url')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='شاخه اصلی')),
            ],
            options={
                'verbose_name': 'شاخه فرعی',
                'verbose_name_plural': 'شاخه های فرعی',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='عنوان محصول')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('quantity', models.IntegerField(default=0, verbose_name='تعداد')),
                ('short_desc', models.CharField(max_length=10000 ,blank=True, null=True, verbose_name='توضیحات')),
                ('offer', models.CharField(max_length= 20 ,db_index=True, default=0, verbose_name='تخفیف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیر فعال')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='عنوان در url')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس 5')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='افزوده شده توسط کاربر')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productsubcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
