# Generated by Django 6.0.5 on 2026-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logo/', verbose_name='لوگو برند'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان برند'),
        ),
    ]
