# Generated by Django 6.0.5 on 2026-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_product_slug_alter_productbrand_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000, null=True, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000, null=True, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000, null=True, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
