# Generated by Django 5.2.14 on 2026-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_product_id_alter_productbrand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='emoji',
            field=models.CharField(max_length=50, null=True, verbose_name='ایموجی'),
        ),
    ]
