# Generated by Django 5.2.14 on 2026-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productbrand_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='emoji',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='emoji',
            field=models.CharField(max_length=50, null=True, verbose_name='ایموجی'),
        ),
    ]
