# Generated by Django 5.2.14 on 2026-06-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_productbrand_emoji_productcategory_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product_module.productcategory', verbose_name='شاخه اصلی'),
        ),
    ]
