# Generated by Django 5.2.14 on 2026-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_productcategory_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='order',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='column',
            field=models.PositiveIntegerField(max_length=10, null=True, verbose_name='ستون'),
        ),
    ]
