# Generated by Django 5.2.14 on 2026-06-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_remove_productcategory_order_productcategory_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product_module.productsubcategory', verbose_name='برند در حوزه'),
        ),
    ]
