# Generated by Django 5.2.14 on 2026-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_productbrand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='category',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productsubcategory', verbose_name='برند در حوزه'),
        ),
    ]
