# Generated by Django 5.2.14 on 2026-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_remove_productbrand_category_productbrand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logo', verbose_name='لوگو برند'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_imgs', verbose_name='عکس زیر شاخه'),
        ),
    ]
