# Generated by Django 5.2.14 on 2026-06-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
