# Generated by Django 5.2.14 on 2026-06-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_product_view_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید'),
        ),
    ]
