# Generated by Django 5.2.14 on 2026-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_alter_product_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(db_index=True, default=0, verbose_name='تخفیف'),
        ),
    ]
