# Generated by Django 5.2.14 on 2026-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_alter_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد امتباز های داده شده'),
        ),
    ]
