# Generated by Django 5.2.14 on 2026-06-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0020_product_rating_product_rating_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='بسته بندی')),
            ],
            options={
                'verbose_name': 'بسته بندی',
                'verbose_name_plural': 'بسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='packs',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.packagesize', verbose_name='اندازه بسته بندی های محصول'),
        ),
    ]
