# Generated by Django 5.2.14 on 2026-06-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_packagesize_product_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_byWeight',
            field=models.BooleanField(default=False, verbose_name='کالای وزنی؟'),
        ),
    ]
