# Generated by Django 5.2.14 on 2026-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0022_product_is_byweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
        ),
    ]
