# Generated by Django 5.2.14 on 2026-06-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_alter_product_quantity_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesize',
            name='size',
            field=models.FloatField(null=True, verbose_name='وزن'),
        ),
    ]
