# Generated by Django 5.2.14 on 2026-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0027_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_Main',
            field=models.BooleanField(default=False, verbose_name='عکس اصلی؟'),
        ),
    ]
