# Generated by Django 5.2.14 on 2026-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0028_productimage_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='روش ارسال')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش های ارسال',
            },
        ),
    ]
