# Generated by Django 5.2.14 on 2026-06-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0029_postingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.postingmethod', verbose_name='روش ارسال'),
        ),
    ]
