# Generated by Django 5.2.14 on 2026-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0030_product_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی'),
        ),
    ]
