# Generated by Django 5.2.14 on 2026-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0031_product_long_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='post',
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.DeleteModel(
            name='PostingMethod',
        ),
    ]
