# Generated by Django 5.2.14 on 2026-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0032_remove_product_post_alter_product_short_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='desc',
            field=models.CharField(max_length=200, verbose_name='توضیحات'),
        ),
    ]
