# Generated by Django 5.2.14 on 2026-06-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0033_alter_productfeature_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='متن نظر')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='product_module.product', verbose_name='برای محصول')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
