# Generated by Django 5.2.14 on 2026-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0034_remove_product_rating_remove_product_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='rating',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
        ),
    ]
