# Generated by Django 5.2.14 on 2026-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0035_alter_productcomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='like',
            field=models.IntegerField(default=0, verbose_name='لایک'),
        ),
    ]
