# Generated by Django 5.2.14 on 2026-06-17 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0037_alter_productcomment_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='like',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
