# Generated by Django 5.2.14 on 2026-06-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0038_remove_productcomment_like_productcomment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='product_module.productcomment', verbose_name='پاسخ به'),
        ),
    ]
