# Generated by Django 5.2.14 on 2026-06-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0039_productcomment_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='parent_id',
        ),
    ]
