# Generated by Django 5.2.14 on 2026-07-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0040_remove_productcomment_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
