# Generated by Django 5.2.14 on 2026-07-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0041_productbrand_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='توضیحات تکمیلی'),
        ),
    ]
