# Generated by Django 5.2.14 on 2026-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0042_remove_product_long_desc_remove_product_short_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='holoo_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بارکد هلو'),
        ),
    ]
