# Generated by Django 5.2.14 on 2026-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0043_product_holoo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='تخفیف'),
        ),
    ]
