# Generated by Django 5.2.14 on 2026-07-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0045_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_weight',
            field=models.CharField(max_length=100 ,blank=True, null=True, verbose_name='وزن بسته'),
        ),
    ]
