# Generated by Django 5.2.14 on 2026-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0046_product_pack_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن بسته'),
        ),
    ]
