# Generated by Django 5.2.14 on 2026-07-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0047_alter_product_pack_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_module.productsubcategory', verbose_name='دسته بندی'),
        ),
    ]
