# Generated by Django 5.2.14 on 2026-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0048_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده؟'),
        ),
    ]
