# Generated by Django 5.2.14 on 2026-07-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0049_productcomment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chosen',
            field=models.BooleanField(default=False, verbose_name='محصول برگزیده'),
        ),
    ]
