# Generated by Django 5.2.14 on 2026-07-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0050_product_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chosen',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محصول برگزیده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='عنوان محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_Main',
            field=models.BooleanField(db_index=True, default=False, verbose_name='عکس اصلی؟'),
        ),
    ]
