# Generated by Django 5.2.14 on 2026-07-19 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0051_alter_product_chosen_alter_product_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='like',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
