# Generated by Django 5.2.14 on 2026-07-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0052_alter_productcomment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='only_in_qaemshahr',
            field=models.BooleanField(db_index=True, default=False, verbose_name='فقط در قائمشهر'),
        ),
    ]
