# Generated by Django 5.2.14 on 2026-07-31 09:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0056_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500000, null=True, verbose_name='توضیحات تکمیلی'),
        ),
    ]
