# Generated by Django 5.2.14 on 2026-07-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0057_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لیبل کالا برای کارت محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_icon',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='آیکون برای لیبل'),
        ),
    ]
