# Generated by Django 5.2.14 on 2026-08-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0059_product_product_listing_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, max_length=500000, null=True, verbose_name='توضیحات'),
        ),
    ]
