# Generated by Django 5.2.14 on 2026-08-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0060_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesize',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='pack_sizes', verbose_name='آیکون'),
        ),
    ]
