# Generated by Django 5.2.14 on 2026-08-07 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0061_packagesize_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_listing_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_deleted', 'chosen', 'quantity', 'view', 'title'], name='product_listing_idx'),
        ),
    ]
