# Generated by Django 6.0.5 on 2026-05-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد فعالسازی')),
                ('verify_code_created', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تایید')),
                ('verify_code_used', models.BooleanField(default=False, verbose_name='کد تایید مصرف شده؟')),
            ],
            options={
                'verbose_name': 'کد تایید',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.verifycode', verbose_name='کد تایید'),
        ),
    ]
