# Generated by Django 6.0.5 on 2026-05-28 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_verify_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify_code',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
