# Generated by Django 6.0.5 on 2026-05-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_remove_user_verify_code_verifycode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.verifycode', verbose_name='کد تایید'),
        ),
    ]
