# Generated by Django 6.0.5 on 2026-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_remove_verifycode_user_user_verify_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='verify_code',
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='verify_code_created',
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='verify_code_used',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد فعالسازی'),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تایید'),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='isUsed',
            field=models.BooleanField(default=False, verbose_name='کد تایید مصرف شده؟'),
        ),
    ]
