# Generated by Django 6.0.5 on 2026-05-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_remove_verifycode_verify_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.verifycode', verbose_name='کد تایید'),
        ),
    ]
