# Generated by Django 6.0.5 on 2026-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد فعالسازی'),
        ),
        migrations.DeleteModel(
            name='VerifyCode',
        ),
    ]
