# Generated by Django 5.2.14 on 2026-05-31 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان آدرس')),
                ('postal_code', models.IntegerField(blank=True, db_index=True, max_length=10, null=True, verbose_name='کد پستی 10 رقمی')),
                ('number_plate', models.IntegerField(blank=True, default=0, max_length=8, null=True, verbose_name='پلاک')),
                ('details', models.CharField(blank=True, max_length=1000, null=True, verbose_name='جزئیات آدرس')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره ثابت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
