# Generated by Django 5.2.14 on 2026-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0013_remove_user_address_alter_user_id_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=1000,blank=True, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=1000 ,blank=True, null=True, verbose_name='استان'),
        ),
    ]
