# Generated by Django 5.2.14 on 2026-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0014_alter_address_options_address_city_address_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_Default',
            field=models.BooleanField(default=False, verbose_name='آدرس پیشفرض'),
        ),
    ]
