# Generated by Django 5.2.14 on 2026-06-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0015_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number_plate',
            field=models.CharField(blank=True, default=0, max_length=8, null=True, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='کد پستی 10 رقمی'),
        ),
    ]
