# Generated by Django 5.2.14 on 2026-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0016_alter_address_number_plate_alter_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='can_delete',
            field=models.BooleanField(default=True, verbose_name='قابلیت حذف'),
        ),
    ]
