# Generated by Django 5.2.14 on 2026-06-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0019_notification_is_seen_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پیام')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام آماده',
                'verbose_name_plural': 'پیام های آماده',
            },
        ),
    ]
