# Generated by Django 5.2.14 on 2026-06-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0020_notificationtexts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationTexts',
        ),
    ]
