# Generated by Django 5.2.14 on 2026-06-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0021_delete_notificationtexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='receiver',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام دریافت کننده'),
        ),
    ]
