# Generated by Django 5.2.14 on 2026-06-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0022_address_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify_code',
        ),
    ]
