# Generated by Django 5.2.14 on 2026-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0023_remove_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='استان'),
        ),
    ]
