# Generated by Django 5.2.14 on 2026-07-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0024_alter_address_city_alter_address_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره بن شده')),
            ],
            options={
                'verbose_name': 'شماره بن شده',
                'verbose_name_plural': 'لیست سیاه',
            },
        ),
    ]
