# Generated by Django 5.2.14 on 2026-07-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0025_restrictedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictedlist',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='شماره بن شده'),
        ),
    ]
