# Generated by Django 5.2.14 on 2026-07-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0026_alter_restrictedlist_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestrictedList',
            new_name='BlackList',
        ),
    ]
