# Generated by Django 5.2.14 on 2026-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0027_rename_restrictedlist_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='شماره بن شده'),
        ),
    ]
