# Generated by Django 5.2.14 on 2026-07-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0028_alter_blacklist_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlackList',
            new_name='BlackList_phones',
        ),
    ]
