# Generated by Django 5.2.14 on 2026-06-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
        ('product_module', '0030_product_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='pack_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.packagesize', verbose_name='اندازه بسته بندی'),
        ),
    ]
