# Generated by Django 5.2.14 on 2026-06-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0016_alter_address_number_plate_alter_address_postal_code'),
        ('order_module', '0002_alter_orderdetail_pack_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_module.address', verbose_name='آدرس سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='توضیحات سفارش'),
        ),
    ]
