# Generated by Django 5.2.14 on 2026-06-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_order_address_order_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='روش پرداخت')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش های پرداخت',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order_module.paymentmethod', verbose_name='روش پرداخت'),
        ),
    ]
