# Generated by Django 5.2.14 on 2026-06-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_paymentmethod_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='روش ارسال')),
                ('price', models.IntegerField(verbose_name='هزینه')),
            ],
        ),
    ]
