# Generated by Django 5.2.14 on 2026-06-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_postingmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='کارت')),
                ('card_code', models.IntegerField(max_length=16, verbose_name='شماره کارت')),
                ('shaba', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا با IR')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'کارت',
                'verbose_name_plural': 'کارت ها',
            },
        ),
        migrations.AlterModelOptions(
            name='postingmethod',
            options={'verbose_name': 'روش ارسال', 'verbose_name_plural': 'روش های ارسال'},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postingmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='order_module.cards', verbose_name='کارت'),
            preserve_default=False,
        ),
    ]
