# Generated by Django 5.2.14 on 2026-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_cards_alter_postingmethod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_code',
            field=models.CharField(max_length=16, verbose_name='شماره کارت'),
        ),
    ]
