# Generated by Django 5.2.14 on 2026-06-21 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0008_alter_cards_is_active_alter_paymentmethod_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order_module.cards', verbose_name='کارت'),
        ),
    ]
