# Generated by Django 5.2.14 on 2026-06-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0009_alter_paymentmethod_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='posting_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order_module.postingmethod', verbose_name='روش ارسال'),
        ),
    ]
