# Generated by Django 5.2.14 on 2026-06-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0010_order_posting_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmethod',
            name='max_weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محدوده وزنی'),
        ),
    ]
