# Generated by Django 5.2.14 on 2026-06-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0011_postingmethod_max_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmethod',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
    ]
