# Generated by Django 5.2.14 on 2026-06-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0012_postingmethod_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmethod',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محدوده قیمتی'),
        ),
    ]
