# Generated by Django 5.2.14 on 2026-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0013_postingmethod_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmethod',
            name='order_type',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ترتیب'),
        ),
    ]
