# Generated by Django 5.2.14 on 2026-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0014_postingmethod_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmethod',
            name='icon',
            field=models.CharField(max_length=1000 ,blank=True, null=True, verbose_name='آیکون'),
        ),
    ]
