# Generated by Django 5.2.14 on 2026-06-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0015_postingmethod_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingmethod',
            name='max_weight',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='محدوده وزنی'),
        ),
    ]
