# Generated by Django 5.2.14 on 2026-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0016_alter_postingmethod_max_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmethod',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='زمان ارسال'),
        ),
    ]
