# Generated by Django 5.2.14 on 2026-06-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0017_postingmethod_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingmethod',
            name='price',
            field=models.IntegerField(verbose_name='نرخ'),
        ),
    ]
