# Generated by Django 5.2.14 on 2026-06-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0018_alter_postingmethod_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postingmethod',
            name='price',
        ),
        migrations.AddField(
            model_name='postingmethod',
            name='price_per_k',
            field=models.PositiveIntegerField(default=1, verbose_name='نرخ بر کیلو'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postingmethod',
            name='price_single',
            field=models.IntegerField(default=2, verbose_name='نرخ معمولی'),
            preserve_default=False,
        ),
    ]
