# Generated by Django 5.2.14 on 2026-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0019_remove_postingmethod_price_postingmethod_price_per_k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
    ]
