# Generated by Django 5.2.14 on 2026-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0020_paymentmethod_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts', verbose_name='رسید واریزی'),
        ),
    ]
