# Generated by Django 5.2.14 on 2026-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0021_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='به نام'),
        ),
    ]
