# Generated by Django 5.2.14 on 2026-06-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0022_cards_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='پایان یافته'),
        ),
    ]
