# Generated by Django 5.2.14 on 2026-06-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0025_remove_order_phone_remove_order_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='steps',
            field=models.ManyToManyField(blank=True, null=True, to='order_module.orderstatus', verbose_name='مراحل'),
        ),
    ]
