# Generated by Django 5.2.14 on 2026-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0026_paymentmethod_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='progress_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='میزان پیشرفت به درصد'),
        ),
    ]
