# Generated by Django 5.2.14 on 2026-06-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0027_orderstatus_progress_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='آیکون'),
        ),
    ]
