# Generated by Django 5.2.14 on 2026-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0028_orderstatus_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
