# Generated by Django 5.2.14 on 2026-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0029_orderstatus_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finalized_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی'),
        ),
    ]
