# Generated by Django 5.2.14 on 2026-07-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0030_order_finalized_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره تراکنش'),
        ),
    ]
