# Generated by Django 5.2.14 on 2026-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0032_paymentmethod_merchant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='مرچنت آیدی'),
        ),
        migrations.AlterField(
            model_name='postingmethod',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='آیکون'),
        ),
    ]
