# Generated by Django 5.2.14 on 2026-07-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0033_alter_paymentmethod_merchant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='پایان یافته'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='postingmethod',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
