# Generated by Django 5.2.14 on 2026-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0034_alter_cards_is_active_alter_order_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
