# Generated by Django 5.2.14 on 2026-07-24 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0029_rename_blacklist_blacklist_phones'),
        ('order_module', '0035_alter_order_payment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmethod',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='زمان برای ارسال به عدد'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'is_paid', 'is_done', 'payment_date'], name='idx_order_pending_close'),
        ),
    ]
