# Generated by Django 5.2.14 on 2026-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0036_postingmethod_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تغییرات'),
        ),
    ]
