# Generated by Django 5.2.14 on 2026-07-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0037_order_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='insufficient',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='آیتم کافی؟'),
        ),
    ]
