# Generated by Django 5.2.14 on 2026-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0038_orderdetail_insufficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='insufficient',
            field=models.BooleanField(db_index=True, default=False, verbose_name='آیتم کافی؟'),
        ),
    ]
