# Generated by Django 5.2.14 on 2026-07-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0040_alter_orderdetail_insufficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reservation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان رزرو موجودی'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(default=False, verbose_name='موجودی رزرو شده؟'),
        ),
    ]
