# Generated by Django 5.2.14 on 2026-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0041_order_stock_reservation_time_order_stock_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmethod',
            name='tex',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ارزش افزوده'),
        ),
    ]
