# Generated by Django 5.2.14 on 2026-07-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0042_postingmethod_tex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postingmethod',
            old_name='tex',
            new_name='tax',
        ),
    ]
