# Generated by Django 5.2.14 on 2026-07-27 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0029_rename_blacklist_blacklist_phones'),
        ('order_module', '0043_rename_tex_postingmethod_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='idx_order_pending_close',
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_reservation_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان رزرو موجودی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='موجودی رزرو شده؟'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'is_paid', 'is_done', 'payment_date', 'stock_reserved', 'stock_reservation_time'], name='idx_order_pending_close'),
        ),
    ]
