# Generated by Django 5.2.14 on 2026-07-27 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0029_rename_blacklist_blacklist_phones'),
        ('order_module', '0044_remove_order_idx_order_pending_close_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='idx_order_pending_close',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stock_reservation_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stock_reserved',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'is_paid', 'is_done', 'payment_date'], name='idx_order_pending_close'),
        ),
    ]
