# Generated by Django 5.2.14 on 2026-07-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0045_remove_order_idx_order_pending_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fail_state',
            field=models.CharField(max_length=100 , db_index=True, default=False, verbose_name='پرداخت شده و ناموفق؟'),
        ),
        migrations.AddField(
            model_name='order',
            name='postage_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه ارسال'),
        ),
    ]
