# Generated by Django 5.2.14 on 2026-07-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0046_order_fail_state_order_postage_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fail_state',
            field=models.BooleanField(db_index=True, default=False, verbose_name='پرداخت شده و ناموفق؟'),
        ),
    ]
