# Generated by Django 5.2.14 on 2026-07-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0049_order_fail_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fail_state',
        ),
    ]
