# Generated by Django 5.2.14 on 2026-07-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0050_remove_order_fail_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fail_state',
            field=models.BooleanField(db_index=True, default=False, verbose_name='پرداخت شده و ناموفق؟'),
        ),
    ]
