# Generated by Django 5.2.14 on 2026-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0051_order_fail_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='زمان از')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='زمان تا')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='تعداد استفاده')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بار استفاده شده')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال؟')),
                ('value', models.IntegerField(verbose_name='مبلغ')),
                ('min_order_amount', models.IntegerField(blank=True, null=True, verbose_name='حداقل مبلغ سبد خرید')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف'),
        ),
    ]
