# Generated by Django 5.2.14 on 2026-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0052_discountcode_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(db_index=True, max_length=15, unique=True, verbose_name='کد'),
        ),
    ]
