# Generated by Django 5.2.14 on 2026-08-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0053_alter_discountcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='value_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف به درصد'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.discountcode', verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مبلغ'),
        ),
    ]
