# Generated by Django 5.2.14 on 2026-08-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0054_remove_order_discount_discountcode_value_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد'),
        ),
    ]
