# Generated by Django 5.2.14 on 2026-07-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel_module', '0002_alter_activeuser_session_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveUser',
        ),
    ]
