# Generated by Django 5.2.14 on 2026-06-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_to_read',
            field=models.IntegerField(default=0, verbose_name='زمان برای خواندن'),
        ),
    ]
