# Generated by Django 5.2.14 on 2026-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_article_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
